version: '3'

services:

  vpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: vpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn